package handlers

import (
	"encoding/json"
	"log"
	"net/http"
	"time"

	"github.com/gorilla/mux"
)

type Character struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Creator   string    `json:"creator"`
}

var exampleCharacters = []Character{
	{
		ID:        "1",
		Name:      "ExampleCharacter1",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
		Creator:   "ExampleCreator1",
	},
	{
		ID:        "2",
		Name:      "ExampleCharacter2",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
		Creator:   "ExampleCreator2",
	},
	{
		ID:        "3",
		Name:      "ExampleCharacter3",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
		Creator:   "ExampleCreator3",
	},
}

type Handler struct {
	// Database connection or other dependencies can be added here
}

func NewCharacterHandler() *Handler {
	return &Handler{}
}

// GetCharacter fetches a character from the database
func (h *Handler) GetCharacter(w http.ResponseWriter, r *http.Request) {
	log.Println("GetCharacter called")

	params := mux.Vars(r)
	id := params["id"]
	log.Printf("fetching character with id: %s\n", id)
	character := findCharacterByID(id)

	log.Printf("character found: %+v\n", character)

	w.WriteHeader(http.StatusOK)
	w.Header().Set("Content-Type", "application/json")
	e := json.NewEncoder(w)
	e.SetIndent("", "  ")
	e.Encode(character)
}

func findCharacterByID(id string) *Character {
	if id == "" {
		return nil
	}
	for _, c := range exampleCharacters {
		if c.ID == id || c.Name == id {
			return &c
		}
	}
	return nil
}

// ListCharacters lists all characters in the database
func (h *Handler) GetCharacters(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	e := json.NewEncoder(w)
	e.SetIndent("", "  ")
	e.Encode(exampleCharacters)
}

// AddNewCharacter adds a new character to the database
func (h *Handler) AddNewCharacter(w http.ResponseWriter, r *http.Request) {
	log.Println("AddNewCharacter called")

	var character Character
	if err := json.NewDecoder(r.Body).Decode(&character); err != nil {
		log.Printf("error decoding character: %v\n", err)
		http.Error(w, "Invalid character data", http.StatusBadRequest)
		return
	}

	character.ID = "4" // This should be generated by the database
	character.CreatedAt = time.Now()
	character.UpdatedAt = time.Now()

	exampleCharacters = append(exampleCharacters, character)

	w.WriteHeader(http.StatusCreated)
	w.Header().Set("Content-Type", "application/json")
	e := json.NewEncoder(w)
	e.SetIndent("", "  ")
	e.Encode(character)
}

// CharacterRegistration registers a new character in the database
// CharacterUpdate updates a character in the database
// CharacterDelete deletes a character from the database
